version: '2.1'

services:
  mongo:
   image: mongo:latest
   restart: always
   command: "--bind_ip_all --replSet rs0"
  
  mongo-client:
   image: mongo:latest
   volumes: 
   - ./initiate_replica.sh:/scripts/initiate_replica.sh
   entrypoint: 
   - /scripts/initiate_replica.sh
  
  testsamlidp_idp:
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:3000/metadata.xml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3000/auth/saml
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
      SAML_ISSUER: http://localhost:3000/metadata.xml
      SAML_CALLBACK_URL: http://localhost:3000/auth/saml/callback
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8080:8080"
    - "8443:8443"
    volumes:
      - ./users.php:/var/www/simplesamlphp/config/authsources.php

  shraga-proxy:
    environment: 
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_NAME: shragaproxy
      SESSION_SECRET: 123
    image: shragauser/shraga-proxy
    ports:
     - 3000:3000
    depends_on:
     - mongo

  socketio-connector:
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_NAME: kanban
      PORT: 8200
    image: blueaiteam/blueboard-socketio-connector
    ports:
      - 8200:8200
    depends_on:
     - mongo

  blueboard:
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_NAME: kanban
      SESSION_SECRET: 123
      REACT_APP_SOCKETLOCATION: socketio-connector:8200
      PORT: 1337
      ROOT_URL: http://127.0.0.1:1337
      SHRAGA_URL: http://localhost:3000 
      CALLBACK_URL: /auth/shraga
    image: blueaiteam/blueboard
    ports:
      - 1337:1337
    depends_on:
     - mongo
     - socketio-connector